### ISSUE TITLE
Cannot get started in 5 minutes.

### ISSUE THREAD

**Issue by smoriemb** [mROS-base/mros2-host-examples#1]
The tile is just half joking :-)
But, we'd better provide an easier way to experience your mros2 environment.
So, I have ported your mros2 as an MBed library and prepared a example below.
[MBed library]
https://os.mbed.com/users/smoritaemb/code/mbed-mros2/
[Example]
https://os.mbed.com/users/smoritaemb/code/mbed-os-example-mros2/

With this example, we can get started the mros2 with only  these steps below.
1. Prepare these items below. 
 - PC having Ethernet port whose IP address is 192.168.11.x(x is not 2) and docker environment.
 - Mbed board (e.g. NUCLEO F429ZI, F767ZI) having an Ethernet port.
2. Import and build the example above on the Mbed web compiler (an executable Mbed binary will be downloaded).
3. Connect the PC and Mbed Board with USB and LAN cables.
4. Open Serial Console of the Mbed board (9600bps)
5. Drag and drop the executable binary above to the Mbed Board.
   we will get the output like below.
```
mbed mros2 start!
[MROS2LIB] mros2_init task start
mROS 2 initialization is completed
[MROS2LIB] create_node
[MROS2LIB] start creating participant
[MROS2LIB] successfully created participant
[MROS2LIB] create_publisher complete.
[MROS2LIB] create_subscription complete. data memory address=0x2001e170[MROS2LIB] Initilizing Domain complete

ready to pub/sub message
```
6. On the PC console, type the command below.
```
docker run --rm -it --net=host  ros:dashing /bin/bash -c  "source /opt/ros/dashing/setup.bash &&
       cd &&
       git clone https://github.com/mROS-base/mros2-host-examples &&
       cd mros2-host-examples &&
       colcon build && source install/setup.bash &&
       (ros2 run mros2_echoback sub_node &) &&
       echo 'wait for sub_node connection' &&
       sleep 10 &&
       ros2 run mros2_echoback pub_node"
```
Then, we can confirm the communication between the PC and Mbed board via ROS2.
```
Cloning into 'mros2-host-examples'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 35 (delta 14), reused 29 (delta 11), pack-reused 0
Unpacking objects: 100% (35/35), done.
Starting >>> mros2_echoback
Finished <<< mros2_echoback [8.14s]                       

Summary: 1 package finished [8.38s]
wait for sub_node connection
[INFO] [pub_mros2]: Publishing msg: 'Hello, world! 0'
[INFO] [mros2_sub]: Subscribed msg: 'Hello, world! 0'
[INFO] [pub_mros2]: Publishing msg: 'Hello, world! 1'
[INFO] [mros2_sub]: Subscribed msg: 'Hello, world! 1'
[INFO] [pub_mros2]: Publishing msg: 'Hello, world! 2'
[INFO] [mros2_sub]: Subscribed msg: 'Hello, world! 2'
...(SNIPPED)...
```

**Comment by takasehideki** [comment]
@smoriemb what an amazing report! It is not joking but real contribution to the world :D 
I'll try it ASAP. thanks!!

**Comment by takasehideki** [comment]
Fantastic! I could confirm the operation of your work in just 5 minutes!

**Comment by takasehideki** [comment]
I used STM32 NUCLEO-F767ZI as the target, and found typo about baudrate (9660->9600). 
Please forgive us for modifying your post.

And note, I used Mbed web compiler to check the operation.

**Comment by takasehideki** [comment]
@smoriemb Because I'm not so familiar with mbed, please tell me some points.

1. Can your work operate on any board if it is Mbed comatible and has Ethernet port? How about a board with WiFi?
2. Is it possible to manage the source code for Mbed repository on GitHub? It may be useful to keep the code consistency with another target for mROS 2, e.g., [mros2-asp3-f767zi](https://github.com/mROS-base/mros2-asp3-f767zi).
3. Could you change the name of repository? We want to establish code name rules: `mros2-<kernel_name>-<target-board>`. We are happy you can change the repository of your work to `mros2-mbed`. `<target-board>` may be omitted if Q1 is Yes. Please also check it: https://github.com/mROS-base/mros2#supported-platform
4. Could you agree that I will add your work on the above list??

**Comment by takasehideki** [comment]
For Q2, my friend gave me the following information. It may be worth a try.
https://os.mbed.com/blog/entry/Share-your-Github-hosted-code/

**Comment by smoriemb** [comment]
> Fantastic! I could confirm the operation of your work in just 5 minutes!

Amazing！ I didn't expect anyone could do it in only 5 minutes.

>I used STM32 NUCLEO-F767ZI as the target, and found typo about baudrate (9660->9600).
>Please forgive us for modifying your post.

Of course, It's OK.
And, I've modified the last step too because being surprised to find pile of corpses of used containers.

**Comment by smoriemb** [comment]
>1. Can your work operate on any board if it is Mbed comatible and has Ethernet port? How about a board with WiFi?

In my opinion, it strongly depends if the board's network interface is used via lwIP or not.
But, I have no Mbed boards having a WiFi interface so that I cannot confirm if there is any board using lwIP and being capable of running mros2. 
At least, we have to create another sample code to use the WiFi interface, referring the Mbed's sample code. 

>2. Is it possible to manage the source code for Mbed repository on GitHub? It may be useful to keep the code consistency with another target for mROS 2, e.g., mros2-asp3-f767zi.

I've done some trials to import the mros2 library from my GitHub repository as below. But the Mbed web compiler could not handle the sub-module (embeddedRTPS) when we imported it to the project on the web compiler :(
https://os.mbed.com/users/smoritaemb/code/mros2/

**Comment by smoriemb** [comment]
>Could you change the name of repository? We want to establish code name rules: mros2-<kernel_name>-<target-board>. We are happy you can change the repository of your work to mros2-mbed. <target-board> may be omitted if >Q1 is Yes. Please also check it: https://github.com/mROS-base/mros2#supported-platform

As I said above, the repository structure you mentioned seems not to work because the web compiler cannot handle sub-modules.
I know we can handle the GitHub and its sub-module when we use Mbed CLI2. But, I could not implement a procedure to get started in 5 minutes today. It requires to take a bit long time to prepare a dockerfile to generate the CLI2 environment and procedure.

> Could you agree that I will add your work on the above list??

Of course, I agree.

**Comment by smoriemb** [comment]
Today, I implemented another getting started procedure using Mbed CLI2 container as below. If you find it acceptable, I will commit the related files to your repository.
1. Prepare these items below.
- PC having Ethernet port whose IP address is 192.168.11.x(x is not 2) and docker environment.
- Mbed board (e.g. NUCLEO F429ZI, F767ZI) having an Ethernet port.
2. Build Mbed executable binary using Mbed CLI2.
(Please replace F429ZI with F797ZI if you use F767ZI)
```
git clone https://github.com/smoriemb/mros2-mbed
cd mros2-mbed
docker run --rm -it --mount=type=bind,source="$(pwd)",destination=/var/mbed -w /var/mbed \
   ghcr.io/armmbed/mbed-os-env \
   /bin/bash -c "mbed-tools deploy && mbed-tools compile -m NUCLEO_F429ZI -t GCC_ARM"
```
After that, you will find an executable binary is created in the path below.
```
cmake_build/NUCLEO_F429ZI/develop/GCC_ARM/mros2-mbed.bin
```
3. Connect the PC and Mbed Board with USB and LAN cables.
4. Open Serial Console of the Mbed board. (9600bps)
5. Copy the executable binary above to the Mbed Board.
    (you may find it in the Nautilus file manager as NODE_F429ZI or F797ZI).
```
mbed mros2 start!
[MROS2LIB] mros2_init task start
mROS 2 initialization is completed
[MROS2LIB] create_node
[MROS2LIB] start creating participant
[MROS2LIB] successfully created participant
[MROS2LIB] create_publisher complete.
[MROS2LIB] create_subscription complete. data memory address=0x2001e170[MROS2LIB] Initilizing Domain complete

ready to pub/sub message
```
6. On the PC console, type the command below.
```
docker run --rm -it --net=host  ros:dashing /bin/bash -c  "source /opt/ros/dashing/setup.bash &&
       cd &&
       git clone https://github.com/mROS-base/mros2-host-examples &&
       cd mros2-host-examples &&
       colcon build && source install/setup.bash &&
       (ros2 run mros2_echoback sub_node &) &&
       echo 'wait for sub_node connection' &&
       sleep 10 &&
       ros2 run mros2_echoback pub_node"
```
Then, we can confirm the communication between the PC and Mbed board via ROS2.
```
Cloning into 'mros2-host-examples'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 35 (delta 14), reused 29 (delta 11), pack-reused 0
Unpacking objects: 100% (35/35), done.
Starting >>> mros2_echoback
Finished <<< mros2_echoback [8.14s]                       

Summary: 1 package finished [8.38s]
wait for sub_node connection
[INFO] [pub_mros2]: Publishing msg: 'Hello, world! 0'
[INFO] [mros2_sub]: Subscribed msg: 'Hello, world! 0'
[INFO] [pub_mros2]: Publishing msg: 'Hello, world! 1'
[INFO] [mros2_sub]: Subscribed msg: 'Hello, world! 1'
[INFO] [pub_mros2]: Publishing msg: 'Hello, world! 2'
[INFO] [mros2_sub]: Subscribed msg: 'Hello, world! 2'
...(SNIPPED)...
```

**Comment by takasehideki** [comment]
@smoriemb Thanks a lot! I confirmed your repository works fine 🎉  https://github.com/smoriemb/mros2-mbed 
I think your initial work will be completed. Could you prepare README and LICENSE on your repository? You can refer our repository as an example. https://github.com/mROS-base/mros2-asp3-f767zi

**Comment by smoriemb** [comment]
@takasehideki 
> I think your initial work will be completed. Could you prepare README and LICENSE on your repository? You can refer our repository as an example. https://github.com/mROS-base/mros2-asp3-f767zi
Thanks for your feedback.

I have already committed the related files, license and README to your repository.
Could you kindly check it?

If it is OK, this issue shall be resolved because we are able to get started mros2 in 5 minutes :D

**Comment by takasehideki** [comment]
@smoriemb Thank you so much for your awesome effort!
I've done following tasks.

- Make public to https://github.com/mROS-base/mros2-mbed
- add mros2-mbed repo on [the list of supported platform](https://github.com/mROS-base/mros2#supported-platform)
- create new release [mros2 v0.2.0](https://github.com/mROS-base/mros2/releases/tag/v0.2.0)

So, this issue is going to be closed!! 🎉
